#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  sudo ./install.sh --bundle FILE --node-name NAME --domain DOMAIN --email EMAIL [options]

Options:
  --seed MULTIADDR             Bootstrap peer; repeatable.
  --controller-url HTTPS_URL   Enroll this VPS into an existing controller.
  --enrollment-token TOKEN     Single-use token generated by that controller.
  --release-bundle-url URL     URL used when this controller creates new commands.
  --admin-user USER            HTTP Basic user (default: veiron-admin).
  --enable-pool                Enable this VPS as a pool coordinator.
  --pool-address ADDRESS       Dedicated reward address required by --enable-pool.
  --pool-name NAME             Public pool name (default: Veiron Reference Pool).
  --external-proxy             Keep an existing reverse proxy on ports 80/443.
  --skip-firewall              Do not configure UFW.
  --help                       Show this help.

Installs a Veiron Mainnet Candidate validation/bootstrap node, loopback RPC,
indexer, optional pool, and authenticated fleet panel on Ubuntu.
It never installs a miner or wallet; any leftover veiron-miner unit/binary is removed.
EOF
}

bundle=""; node_name=""; domain=""; email=""; controller_url=""; enrollment_token=""
release_bundle_url=""
admin_user="veiron-admin"; skip_firewall=false; external_proxy=false; enable_pool=false; pool_address=""; pool_name="Veiron Reference Pool"; seeds=()

prompt_input() {
  local prompt="$1"
  local default_value="${2:-}"
  local value=""
  if [[ -t 0 ]]; then
    if [[ -n "$default_value" ]]; then
      read -r -p "$prompt [$default_value]: " value
    else
      read -r -p "$prompt: " value
    fi
    value="${value:-$default_value}"
  else
    value="$default_value"
  fi
  printf '%s' "$value"
}

prompt_confirm() {
  local prompt="$1"
  local default_value="${2:-n}"
  local value=""
  if [[ -t 0 ]]; then
    while true; do
      read -r -p "$prompt [$default_value]: " value
      value="${value:-$default_value}"
      case "${value,,}" in
        y|yes) return 0 ;;
        n|no) return 1 ;;
        *) echo "Please answer yes or no." >&2 ;;
      esac
    done
  fi
  return 1
}

while (($#)); do
  case "$1" in
    --bundle) bundle="${2:-}"; shift 2 ;;
    --node-name) node_name="${2:-}"; shift 2 ;;
    --domain|--advertise-host) domain="${2:-}"; shift 2 ;;
    --email) email="${2:-}"; shift 2 ;;
    --seed) seeds+=("${2:-}"); shift 2 ;;
    --controller-url) controller_url="${2:-}"; shift 2 ;;
    --enrollment-token) enrollment_token="${2:-}"; shift 2 ;;
    --release-bundle-url) release_bundle_url="${2:-}"; shift 2 ;;
    --admin-user) admin_user="${2:-}"; shift 2 ;;
    --enable-pool) enable_pool=true; shift ;;
    --pool-address) pool_address="${2:-}"; shift 2 ;;
    --pool-name) pool_name="${2:-}"; shift 2 ;;
    --external-proxy) external_proxy=true; shift ;;
    --skip-firewall) skip_firewall=true; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

fail() { echo "ERROR: $*" >&2; exit 1; }
[[ $EUID -eq 0 ]] || fail "Run with sudo."

default_node_name="$(hostname -s 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]._' '-' | head -c 32 || true)"
default_node_name="${default_node_name:-veiron-vps}"

if [[ -z "$bundle" ]]; then
  bundle="$(prompt_input "Path to the Veiron release archive" "")"
fi
if [[ -z "$node_name" ]]; then
  node_name="$(prompt_input "Node name" "$default_node_name")"
fi
if [[ -z "$domain" ]]; then
  domain="$(prompt_input "Public domain" "")"
fi
if [[ -z "$email" ]]; then
  email="$(prompt_input "Admin email" "")"
fi
if [[ -z "$release_bundle_url" ]]; then
  release_bundle_url="$(prompt_input "Release bundle URL (optional)" "")"
fi
if [[ -z "$admin_user" || "$admin_user" == "veiron-admin" ]]; then
  admin_user="$(prompt_input "Admin username for /control/" "veiron-admin")"
fi
if [[ "$enable_pool" != true ]]; then
  if prompt_confirm "Enable pool coordinator on this VPS?" "n"; then
    enable_pool=true
  fi
fi
if [[ "$enable_pool" == true && -z "$pool_address" ]]; then
  pool_address="$(prompt_input "Pool reward address" "")"
fi
if [[ "$enable_pool" == true && -z "$pool_name" ]]; then
  pool_name="$(prompt_input "Pool name" "Veiron Reference Pool")"
fi
if [[ "$external_proxy" != true ]]; then
  if prompt_confirm "Use an existing reverse proxy on 80/443?" "n"; then
    external_proxy=true
  fi
fi
if [[ "$skip_firewall" != true ]]; then
  if prompt_confirm "Configure UFW firewall?" "y"; then
    skip_firewall=false
  else
    skip_firewall=true
  fi
fi

[[ -n "$bundle" && -f "$bundle" ]] || fail "--bundle must point to the release archive."
[[ "$node_name" =~ ^[A-Za-z0-9._-]{1,64}$ ]] || fail "Invalid --node-name."
[[ "$domain" =~ ^[A-Za-z0-9.-]+$ ]] || fail "Invalid --domain."
[[ "$email" == *@* ]] || fail "Invalid --email."
[[ -z "$release_bundle_url" || "$release_bundle_url" == https://* ]] || fail "--release-bundle-url must be an HTTPS release asset URL or left empty."
grep -qi ubuntu /etc/os-release || fail "Ubuntu is required."
if [[ -n "$controller_url" ]]; then
  [[ "$controller_url" == https://* ]] || fail "--controller-url must use HTTPS."
  [[ -n "$enrollment_token" ]] || fail "--enrollment-token is required with --controller-url."
fi
if [[ "$enable_pool" == true && -z "$pool_address" ]]; then fail "--pool-address is required with --enable-pool."; fi
for seed in "${seeds[@]}"; do
  [[ "$seed" =~ ^/(dns4|ip4|ip6)/.+/tcp/[0-9]+$ ]] || fail "Invalid seed multiaddress: $seed"
done

echo "[1/9] Installing operating-system dependencies"
apt-get update
packages=(ca-certificates curl apache2-utils ufw openssl)
if [[ "$external_proxy" == false ]]; then packages+=(nginx certbot); fi
DEBIAN_FRONTEND=noninteractive apt-get install -y "${packages[@]}"

echo "[2/9] Creating restricted service accounts and directories"
id veiron >/dev/null 2>&1 || useradd --system --home /var/lib/veiron --shell /usr/sbin/nologin veiron
id veiron-control >/dev/null 2>&1 || useradd --system --home /var/lib/veiron-control --shell /usr/sbin/nologin veiron-control
id veiron-pool >/dev/null 2>&1 || useradd --system --home /var/lib/veiron-pool --shell /usr/sbin/nologin veiron-pool
install -d -o root -g root -m 0755 /opt/veiron /etc/veiron /etc/veiron-control
install -d -o veiron -g veiron -m 0750 /var/lib/veiron/.veiron-mainnet/{chain,mempool,indexer,node}
install -d -o veiron-control -g veiron-control -m 0750 /var/lib/veiron-control
install -d -o veiron-pool -g veiron-pool -m 0750 /var/lib/veiron-pool

echo "[3/9] Verifying and staging release bundle"
tmp="$(mktemp -d)"
backup=""
maintenance_started=false
upgrade_complete=false
active_units=()
cleanup() {
  code=$?
  rm -rf "$tmp"
  if [[ $code -ne 0 && "$maintenance_started" == true && "$upgrade_complete" == false ]]; then
    echo "Upgrade failed; restoring the previous Veiron installation." >&2
    systemctl stop veiron-indexer-refresh.timer veiron-mining-pool veiron-vps-admin veiron-rpc veiron-node 2>/dev/null || true
    if [[ -n "$backup" && -f "$backup" ]]; then
      tar -xzf "$backup" -C / || echo "WARNING: automatic file rollback failed; use $backup manually." >&2
    fi
    systemctl daemon-reload || true
    for unit in "${active_units[@]}"; do systemctl start "$unit" || true; done
  fi
}
trap cleanup EXIT
tar --extract --gzip --file "$bundle" --directory "$tmp"
root="$tmp/veiron-vps-control"; [[ -d "$root" ]] || root="$tmp"
for required in bin/veiron-node bin/veiron-rpc-gateway bin/veiron-indexer bin/veiron-vps-admin bin/veiron-mining-pool vps-control-plane/install.sh; do
  [[ -f "$root/$required" ]] || fail "Bundle missing $required"
done
if [[ -d /opt/veiron/bin ]]; then
  backup="/var/lib/veiron-control/pre-upgrade-$(date -u +%Y%m%dT%H%M%SZ).tar.gz"
  backup_paths=()
  for path in /etc/veiron /etc/veiron-control /etc/veiron-pool /var/lib/veiron-pool /opt/veiron; do
    [[ -e "$path" ]] && backup_paths+=("$path")
  done
  tar -czf "$backup" "${backup_paths[@]}"
  chown veiron-control:veiron-control "$backup"
  echo "Existing installation backed up to $backup"
fi
for unit in veiron-node veiron-rpc veiron-vps-admin veiron-mining-pool veiron-indexer-refresh.timer; do
  systemctl is-active --quiet "$unit" 2>/dev/null && active_units+=("$unit")
done
maintenance_started=true
systemctl stop veiron-indexer-refresh.timer veiron-mining-pool veiron-vps-admin veiron-rpc veiron-node 2>/dev/null || true
cp -a "$root/." /opt/veiron/
chmod 0755 /opt/veiron/bin/* /opt/veiron/vps-control-plane/*.sh

echo "[4/9] Rendering network and fleet configuration"
seed_toml=""
for seed in "${seeds[@]}"; do
  escaped="${seed//\\/\\\\}"; escaped="${escaped//\"/\\\"}"
  [[ -n "$seed_toml" ]] && seed_toml+=", "
  seed_toml+="\"$escaped\""
done
# Do not self-dial. Empty seed lists are valid for the first bootstrap VPS.
# Enrolled peers must receive the controller multiaddr via --seed or invitation.
# Listing this host as its own seed produces "Local peer ID" listen errors.
if [[ -z "$seed_toml" ]]; then
  seed_toml=""
fi
sed "s|__SEED_NODES__|$seed_toml|" /opt/veiron/vps-control-plane/configs/node.toml > /etc/veiron/node.toml
sed "s|__PUBLIC_ORIGIN__|https://$domain|" /opt/veiron/vps-control-plane/configs/rpc.toml > /etc/veiron/rpc.toml
controller_toml="\"\""; [[ -n "$controller_url" ]] && controller_toml="\"$controller_url\""
sed -e "s|__NODE_NAME__|$node_name|g" -e "s|__DOMAIN__|$domain|g" \
  -e "s|__RELEASE_BUNDLE_URL__|$release_bundle_url|g" -e "s|__CONTROLLER_URL__|$controller_toml|g" \
  /opt/veiron/vps-control-plane/configs/admin.toml > /etc/veiron-control/admin.toml
chown root:veiron-control /etc/veiron-control/admin.toml; chmod 0640 /etc/veiron-control/admin.toml
if [[ -n "$enrollment_token" ]]; then
  printf '%s' "$enrollment_token" > /var/lib/veiron-control/enrollment.token
  chown veiron-control:veiron-control /var/lib/veiron-control/enrollment.token
  chmod 0600 /var/lib/veiron-control/enrollment.token
fi
if [[ "$enable_pool" == true ]]; then
  install -d -o root -g veiron-pool -m 0750 /etc/veiron-pool
  sed -e "s|__POOL_NAME__|$pool_name|g" -e "s|__POOL_ADDRESS__|$pool_address|g" -e "s|__DOMAIN__|$domain|g" \
    /opt/veiron/vps-control-plane/configs/pool.toml > /etc/veiron-pool/pool.toml
  if [[ ! -f /etc/veiron-pool/admin.token ]]; then openssl rand -hex 32 > /etc/veiron-pool/admin.token; fi
  chown root:veiron-pool /etc/veiron-pool/pool.toml /etc/veiron-pool/admin.token
  chmod 0640 /etc/veiron-pool/pool.toml /etc/veiron-pool/admin.token
fi

echo "[5/9] Validating rendered configuration"
(cd /opt/veiron && bin/veiron-node --config /etc/veiron/node.toml genesis-approval-status >/dev/null)
(cd /opt/veiron && bin/veiron-rpc-gateway --config /etc/veiron/rpc.toml --node-config /etc/veiron/node.toml --check-config)
/opt/veiron/bin/veiron-vps-admin --config /etc/veiron-control/admin.toml --check-config
if [[ "$enable_pool" == true ]]; then /opt/veiron/bin/veiron-mining-pool --config /etc/veiron-pool/pool.toml --check-config; fi

echo "[6/9] Installing services"
install -m 0644 /opt/veiron/vps-control-plane/systemd/* /etc/systemd/system/
# Auto-update agent must be executable for the systemd oneshot.
if [[ -f /opt/veiron/vps-control-plane/auto-update.sh ]]; then
  chmod 0755 /opt/veiron/vps-control-plane/auto-update.sh
fi
systemctl daemon-reload

echo "[7/9] Configuring authenticated HTTPS operator panel"
if [[ -f /etc/veiron-control/admin.htpasswd ]]; then
  admin_credential="unchanged from the previous installation"
else
  admin_credential="$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
  htpasswd -bBc /etc/veiron-control/admin.htpasswd "$admin_user" "$admin_credential" >/dev/null
fi
chmod 0640 /etc/veiron-control/admin.htpasswd; chown root:www-data /etc/veiron-control/admin.htpasswd
if [[ "$external_proxy" == false ]]; then
  sed "s|__DOMAIN__|$domain|g" /opt/veiron/vps-control-plane/nginx/veiron.conf > /etc/nginx/sites-available/veiron
  ln -sfn /etc/nginx/sites-available/veiron /etc/nginx/sites-enabled/veiron
  rm -f /etc/nginx/sites-enabled/default
  if [[ ! -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]]; then
    rm -f /etc/nginx/sites-enabled/veiron
    systemctl stop nginx || true
    certbot certonly --standalone --non-interactive --agree-tos --email "$email" -d "$domain"
    ln -s /etc/nginx/sites-available/veiron /etc/nginx/sites-enabled/veiron
  fi
  nginx -t
  systemctl enable --now nginx
else
  echo "Existing reverse proxy preserved; configure /control/, /fleet/ and optional /pool/ upstreams manually."
fi

echo "[8/9] Applying host firewall"
if [[ "$skip_firewall" == false ]]; then
  ufw allow OpenSSH; ufw allow 80/tcp; ufw allow 443/tcp; ufw allow 20787/tcp; ufw --force enable
fi

echo "[9/9] Starting and checking Veiron services"
# Policy: this host is node + RPC + optional pool + control-plane only.
# Never run a local miner on the VPS (desktop/CLI miners connect remotely).
systemctl stop veiron-miner 2>/dev/null || true
systemctl disable veiron-miner 2>/dev/null || true
systemctl mask veiron-miner 2>/dev/null || true
rm -f /etc/systemd/system/veiron-miner.service \
  /etc/systemd/system/multi-user.target.wants/veiron-miner.service \
  /opt/veiron/bin/veiron-miner
rm -rf /etc/veiron-miner /var/lib/veiron-miner
systemctl daemon-reload 2>/dev/null || true

systemctl enable --now veiron-node veiron-rpc veiron-vps-admin veiron-indexer-refresh.timer
# Silent GitHub auto-update for node/rpc/indexer/admin/pool — no operator approval.
if [[ -f /etc/systemd/system/veiron-auto-update.timer ]]; then
  systemctl enable --now veiron-auto-update.timer
  log_auto="enabled"
else
  log_auto="missing unit"
fi
if [[ "$enable_pool" == true ]]; then systemctl enable --now veiron-mining-pool; else systemctl disable --now veiron-mining-pool 2>/dev/null || true; fi
sleep 4
if [[ "$external_proxy" == true ]]; then
  /opt/veiron/vps-control-plane/health-check.sh --domain "$domain" --local-only
else
  /opt/veiron/vps-control-plane/health-check.sh --domain "$domain"
fi
upgrade_complete=true

cat <<EOF

Veiron VPS installation completed.
P2P:          /dns4/$domain/tcp/20787
Public RPC:   https://$domain
Fleet status: https://$domain/fleet/status
Admin panel:  https://$domain/control/
Admin user:   $admin_user
Admin password (shown once): $admin_credential
Reverse proxy: $(if [[ "$external_proxy" == true ]]; then echo external; else echo managed-nginx; fi)
Auto-update:  GitHub Releases polled every 15m ($log_auto) — applies without approval

Store that password in an operator password manager. It is not written in plaintext.
This is Mainnet Candidate / Prototype infrastructure, not a live-mainnet declaration.
EOF
